apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "podsync.fullname" . }}
  labels:
    {{- include "podsync.labels" . | nindent 4 }}
{{- if .Values.configuration.reloaderEnabled }}
  annotations:
    configmap.reloader.stakater.com/reload: "{{ include "podsync.fullname" . }}-config"
{{- end }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "podsync.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "podsync.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "podsync.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          volumeMounts:
            {{- if .Values.persistence.dataClaimName }}
            - mountPath: /app/data
              name: data
            {{- end }}
            - mountPath: /app/config.toml
              name: config-final
              subPath: config.toml
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      initContainers:
        - name: {{ .Chart.Name }}-init-config
          image: dibi/envsubst
          imagePullPolicy: IfNotPresent
          env:
            {{- if .Values.ingress.enabled }}
            - name: PODSYNC_INGRESS_HOST
              value: {{ default "localhost" .Values.ingress.host }}
            {{- end }}
            {{- toYaml .Values.configuration.env | nindent 12 }}
          volumeMounts:
            - mountPath: /workdir
              name: config-template
            - mountPath: /processed
              name: config-final
      volumes:
        - name: config-template
          configMap:
            name: {{ include "podsync.fullname" . }}-config
        - name: config-final
          emptyDir: {}
        {{- if .Values.persistence.dataClaimName }}
        - name: data
          persistentVolumeClaim:
            claimName: {{ .Values.persistence.dataClaimName }}
        {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
