apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "podsync.fullname" . }}
  labels:
    {{- include "podsync.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "podsync.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "podsync.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "podsync.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- if .Values.configTemplateName }}
      initContainers:
        - name: {{ .Chart.Name }}-init-config
          image: dibi/envsubst
          imagePullPolicy: IfNotPresent
          env:
            {{- if .Values.ingress.enabled }}
            - name: PODSYNC_INGRESS_HOST
              value: {{ default "localhost" .Values.ingress.host }}
            {{- end }}
            {{- toYaml .Values.templateVariables | nindent 12 }}
          volumeMounts:
            - mountPath: /workdir
              name: config-template
            - mountPath: /processed
              name: config-final
      {{- end }}
      volumes:
        {{- if .Values.configTemplateName }}
        - name: config-template
          configMap:
            name: {{ .Values.configTemplateName }}
        {{- end }}
        - name: config-final
          emptyDir: {}
        {{- if .Values.dataClaimName }}
        - name: data
          persistentVolumeClaim:
            claimName: {{ .Values.dataClaimName }}
        {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
